name: Update List

on:
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch JSON data
        run: |
          curl -o list.json https://api.travellings.cn/all

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add list.json
          git commit -m "Update list.json with latest data" || echo "No changes to commit"
          git push origin HEAD:main